# Generated by Django 2.2.17 on 2021-01-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Middle Name'),
        ),
    ]
