# Generated by Django 2.2.17 on 2021-01-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='middle_name',
        ),
    ]
