# Generated by Django 2.2.17 on 2021-02-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210204_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='TigraAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=40, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Тигра Админ',
                'verbose_name_plural': 'Тигра Админы',
            },
        ),
    ]
